server:
    port: 8874
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8881/eureka/,http://peer3:8883/eureka/,http://peer2:8882/eureka/
spring:
  application:
    name: zuul-server
zuul:
  routes:
  # 集成 eureka 可以不必配置下面路由转发规则，可以直接通过serviceId访问服务
  #/api-a/ 开头匹配到service-producer
    product-service:
      path: /productService/**
      serviceId: product-server
  #/api-b/ 开头匹配到service-producer
    user-service:
      path: /userService/**
      serviceId: user-server
    feign-service:
      path: /feignService/**
      serviceId: consumer-feign
    ribbon-service:
      path: /ribbonService/**
      serviceId: consumer-ribbon
  #匹配/github/直接重定向到https://github.com/
    github:
      path: /github/**
      url: https://www.baidu.com/