server:
    port: 8877
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8881/eureka/,http://peer3:8883/eureka/,http://peer2:8882/eureka/
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          # 是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled: true
          # 默认服务名称必须大写 访问 true 小写即可访问
          lower-case-service-id: true
      routes:
        # 路由ID
        - id: user-server
          # 目标服务地址 注册中心服务ID
          uri: lb://user-server
          predicates:
            # 路由条件
            - Path=/user/**