server:
    port: 8873
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8881/eureka/,http://peer3:8883/eureka/,http://peer2:8882/eureka/
spring:
  application:
    name: consumer-feign
#开启Hystrix
feign:
  hystrix:
    enabled: true
